import { QuizStep, FragranceNote, NoteCategory } from '@/types';

// Comprehensive fragrance notes organized by category
// All icons are Lucide icon names — rendered via RenderIcon component
export const fragranceNotes: Record<string, FragranceNote[]> = {
    freshCitrus: [
        { id: 'bergamot', label: 'Bergamot', labelAr: 'برغموت', icon: 'Citrus' },
        { id: 'lemon', label: 'Lemon', labelAr: 'ليمون', icon: 'Droplets' },
        { id: 'lime', label: 'Lime', labelAr: 'ليمون أخضر', icon: 'Droplets' },
        { id: 'grapefruit', label: 'Grapefruit', labelAr: 'جريب فروت', icon: 'Citrus' },
        { id: 'orange', label: 'Orange', labelAr: 'برتقال', icon: 'Citrus' },
        { id: 'mandarin', label: 'Mandarin', labelAr: 'يوسفي', icon: 'Citrus' },
        { id: 'yuzu', label: 'Yuzu', labelAr: 'يوزو', icon: 'Droplets' },
        { id: 'neroli', label: 'Neroli', labelAr: 'نيرولي', icon: 'Flower2' },
        { id: 'petitgrain', label: 'Petitgrain', labelAr: 'بيتي جران', icon: 'LeafyGreen' },
        { id: 'green-apple', label: 'Green Apple', labelAr: 'تفاح أخضر', icon: 'Apple' },
        { id: 'pear', label: 'Pear', labelAr: 'كمثرى', icon: 'Droplets' },
        { id: 'cucumber', label: 'Cucumber', labelAr: 'خيار', icon: 'Droplets' },
        { id: 'mint', label: 'Mint', labelAr: 'نعناع', icon: 'LeafyGreen' },
        { id: 'basil', label: 'Basil', labelAr: 'ريحان', icon: 'LeafyGreen' },
        { id: 'green-tea', label: 'Green Tea', labelAr: 'شاي أخضر', icon: 'LeafyGreen' },
        { id: 'bamboo', label: 'Bamboo', labelAr: 'خيزران', icon: 'TreePine' },
        { id: 'lotus', label: 'Lotus', labelAr: 'لوتس', icon: 'Flower2' },
        { id: 'water-lily', label: 'Water Lily', labelAr: 'زنبق الماء', icon: 'Flower2' },
        { id: 'marine', label: 'Marine/Aquatic', labelAr: 'بحري', icon: 'Waves' },
        { id: 'ozone', label: 'Ozone', labelAr: 'أوزون', icon: 'Wind' },
    ],
    floral: [
        { id: 'rose', label: 'Rose', labelAr: 'ورد', icon: 'Flower2' },
        { id: 'jasmine', label: 'Jasmine', labelAr: 'ياسمين', icon: 'Flower' },
        { id: 'tuberose', label: 'Tuberose', labelAr: 'تيوبروز', icon: 'Flower' },
        { id: 'iris', label: 'Iris/Orris', labelAr: 'سوسن', icon: 'Flower2' },
        { id: 'lily-valley', label: 'Lily of the Valley', labelAr: 'زنبق الوادي', icon: 'Flower2' },
        { id: 'orange-blossom', label: 'Orange Blossom', labelAr: 'زهر البرتقال', icon: 'Flower2' },
        { id: 'ylang', label: 'Ylang Ylang', labelAr: 'يلانج يلانج', icon: 'Flower' },
        { id: 'peony', label: 'Peony', labelAr: 'فاوانيا', icon: 'Flower2' },
        { id: 'magnolia', label: 'Magnolia', labelAr: 'ماغنوليا', icon: 'Flower' },
        { id: 'gardenia', label: 'Gardenia', labelAr: 'غاردينيا', icon: 'Flower' },
        { id: 'violet', label: 'Violet', labelAr: 'بنفسج', icon: 'Flower2' },
        { id: 'lavender', label: 'Lavender', labelAr: 'لافندر', icon: 'Flower2' },
        { id: 'geranium', label: 'Geranium', labelAr: 'إبرة الراعي', icon: 'LeafyGreen' },
        { id: 'carnation', label: 'Carnation', labelAr: 'قرنفل', icon: 'Flower2' },
        { id: 'osmanthus', label: 'Osmanthus', labelAr: 'أوسمانثوس', icon: 'Flower' },
        { id: 'frangipani', label: 'Frangipani', labelAr: 'فرانجيباني', icon: 'Flower' },
        { id: 'cherry-blossom', label: 'Cherry Blossom', labelAr: 'زهر الكرز', icon: 'Flower2' },
        { id: 'honeysuckle', label: 'Honeysuckle', labelAr: 'زهر العسل', icon: 'Flower' },
        { id: 'freesia', label: 'Freesia', labelAr: 'فريزيا', icon: 'Flower2' },
        { id: 'hibiscus', label: 'Hibiscus', labelAr: 'كركديه', icon: 'Flower' },
    ],
    sweetGourmand: [
        { id: 'vanilla', label: 'Vanilla', labelAr: 'فانيليا', icon: 'Droplets' },
        { id: 'caramel', label: 'Caramel', labelAr: 'كراميل', icon: 'Droplets' },
        { id: 'praline', label: 'Praline', labelAr: 'برالين', icon: 'Nut' },
        { id: 'chocolate', label: 'Chocolate', labelAr: 'شوكولاتة', icon: 'Coffee' },
        { id: 'coffee', label: 'Coffee', labelAr: 'قهوة', icon: 'Coffee' },
        { id: 'honey', label: 'Honey', labelAr: 'عسل', icon: 'Droplets' },
        { id: 'cotton-candy', label: 'Cotton Candy', labelAr: 'غزل البنات', icon: 'Sparkle' },
        { id: 'almond', label: 'Almond', labelAr: 'لوز', icon: 'Nut' },
        { id: 'coconut', label: 'Coconut', labelAr: 'جوز الهند', icon: 'Circle' },
        { id: 'marshmallow', label: 'Marshmallow', labelAr: 'مارشميلو', icon: 'CloudSnow' },
        { id: 'toffee', label: 'Toffee', labelAr: 'توفي', icon: 'Droplets' },
        { id: 'brown-sugar', label: 'Brown Sugar', labelAr: 'سكر بني', icon: 'Droplets' },
        { id: 'maple', label: 'Maple', labelAr: 'قيقب', icon: 'Leaf' },
        { id: 'rum', label: 'Rum', labelAr: 'روم', icon: 'Wine' },
        { id: 'cognac', label: 'Cognac', labelAr: 'كونياك', icon: 'Wine' },
        { id: 'bubblegum', label: 'Bubblegum', labelAr: 'علكة', icon: 'Circle' },
        { id: 'cake', label: 'Cake', labelAr: 'كيك', icon: 'Cookie' },
        { id: 'cream', label: 'Cream', labelAr: 'كريمة', icon: 'Droplets' },
        { id: 'milk', label: 'Milk', labelAr: 'حليب', icon: 'Droplets' },
        { id: 'ice-cream', label: 'Ice Cream', labelAr: 'آيس كريم', icon: 'CloudSnow' },
    ],
    woody: [
        { id: 'sandalwood', label: 'Sandalwood', labelAr: 'صندل', icon: 'TreePine' },
        { id: 'cedar', label: 'Cedar', labelAr: 'أرز', icon: 'Trees' },
        { id: 'oud', label: 'Oud/Agarwood', labelAr: 'عود', icon: 'TreePine' },
        { id: 'vetiver', label: 'Vetiver', labelAr: 'فيتيفر', icon: 'LeafyGreen' },
        { id: 'patchouli', label: 'Patchouli', labelAr: 'باتشولي', icon: 'LeafyGreen' },
        { id: 'guaiac', label: 'Guaiac Wood', labelAr: 'خشب الغاياك', icon: 'TreePine' },
        { id: 'birch', label: 'Birch', labelAr: 'بتولا', icon: 'Trees' },
        { id: 'pine', label: 'Pine', labelAr: 'صنوبر', icon: 'TreePine' },
        { id: 'cypress', label: 'Cypress', labelAr: 'سرو', icon: 'Trees' },
        { id: 'juniper', label: 'Juniper', labelAr: 'عرعر', icon: 'TreePine' },
        { id: 'driftwood', label: 'Driftwood', labelAr: 'خشب طافي', icon: 'TreePine' },
        { id: 'teakwood', label: 'Teakwood', labelAr: 'خشب الساج', icon: 'TreePine' },
        { id: 'rosewood', label: 'Rosewood', labelAr: 'خشب الورد', icon: 'TreePine' },
        { id: 'ebony', label: 'Ebony', labelAr: 'أبنوس', icon: 'TreePine' },
        { id: 'mahogany', label: 'Mahogany', labelAr: 'ماهوجني', icon: 'TreePine' },
        { id: 'bamboo-wood', label: 'Bamboo Wood', labelAr: 'خشب الخيزران', icon: 'TreePine' },
        { id: 'cashmeran', label: 'Cashmeran', labelAr: 'كشميران', icon: 'Sparkle' },
        { id: 'iso-e-super', label: 'Iso E Super', labelAr: 'إيزو إي سوبر', icon: 'Sparkle' },
        { id: 'akigalawood', label: 'Akigalawood', labelAr: 'أكيغالاوود', icon: 'TreePine' },
        { id: 'hinoki', label: 'Hinoki', labelAr: 'هينوكي', icon: 'TreePine' },
    ],
    spicy: [
        { id: 'black-pepper', label: 'Black Pepper', labelAr: 'فلفل أسود', icon: 'Flame' },
        { id: 'pink-pepper', label: 'Pink Pepper', labelAr: 'فلفل وردي', icon: 'Flower2' },
        { id: 'cardamom', label: 'Cardamom', labelAr: 'هيل', icon: 'Nut' },
        { id: 'cinnamon', label: 'Cinnamon', labelAr: 'قرفة', icon: 'Flame' },
        { id: 'clove', label: 'Clove', labelAr: 'قرنفل', icon: 'Flame' },
        { id: 'nutmeg', label: 'Nutmeg', labelAr: 'جوزة الطيب', icon: 'Nut' },
        { id: 'ginger', label: 'Ginger', labelAr: 'زنجبيل', icon: 'Flame' },
        { id: 'saffron', label: 'Saffron', labelAr: 'زعفران', icon: 'Flame' },
        { id: 'cumin', label: 'Cumin', labelAr: 'كمون', icon: 'Nut' },
        { id: 'coriander', label: 'Coriander', labelAr: 'كزبرة', icon: 'LeafyGreen' },
        { id: 'star-anise', label: 'Star Anise', labelAr: 'يانسون نجمي', icon: 'Star' },
        { id: 'incense', label: 'Incense/Frankincense', labelAr: 'بخور/لبان', icon: 'Flame' },
        { id: 'myrrh', label: 'Myrrh', labelAr: 'مر', icon: 'Droplets' },
        { id: 'elemi', label: 'Elemi', labelAr: 'إيليمي', icon: 'LeafyGreen' },
        { id: 'bay-leaf', label: 'Bay Leaf', labelAr: 'ورق غار', icon: 'Leaf' },
        { id: 'paprika', label: 'Paprika', labelAr: 'بابريكا', icon: 'Flame' },
        { id: 'chili', label: 'Chili', labelAr: 'فلفل حار', icon: 'Flame' },
        { id: 'wasabi', label: 'Wasabi', labelAr: 'واسابي', icon: 'LeafyGreen' },
    ],
    amberyResinous: [
        { id: 'amber', label: 'Amber', labelAr: 'عنبر', icon: 'Gem' },
        { id: 'labdanum', label: 'Labdanum', labelAr: 'لابدانوم', icon: 'Droplets' },
        { id: 'benzoin', label: 'Benzoin', labelAr: 'بنزوين', icon: 'Droplets' },
        { id: 'tonka', label: 'Tonka Bean', labelAr: 'تونكا', icon: 'Nut' },
        { id: 'coumarin', label: 'Coumarin', labelAr: 'كومارين', icon: 'LeafyGreen' },
        { id: 'styrax', label: 'Styrax', labelAr: 'ستيراكس', icon: 'Droplets' },
        { id: 'opoponax', label: 'Opoponax', labelAr: 'أوبوبوناكس', icon: 'Droplets' },
        { id: 'peru-balsam', label: 'Peru Balsam', labelAr: 'بلسم بيرو', icon: 'Droplets' },
        { id: 'tolu-balsam', label: 'Tolu Balsam', labelAr: 'بلسم تولو', icon: 'Droplets' },
        { id: 'ambergris', label: 'Ambergris', labelAr: 'عنبر حوتي', icon: 'Waves' },
        { id: 'castoreum', label: 'Castoreum', labelAr: 'كاستوريوم', icon: 'Squirrel' },
        { id: 'civet', label: 'Civet', labelAr: 'زباد', icon: 'HelpCircle' },
        { id: 'beeswax', label: 'Beeswax', labelAr: 'شمع النحل', icon: 'Droplets' },
    ],
    musky: [
        { id: 'white-musk', label: 'White Musk', labelAr: 'مسك أبيض', icon: 'Circle' },
        { id: 'skin-musk', label: 'Skin Musk', labelAr: 'مسك الجلد', icon: 'User' },
        { id: 'ambroxan', label: 'Ambroxan', labelAr: 'أمبروكسان', icon: 'Sparkle' },
        { id: 'muscone', label: 'Muscone', labelAr: 'مسكون', icon: 'Circle' },
        { id: 'egyptian-musk', label: 'Egyptian Musk', labelAr: 'مسك مصري', icon: 'Shield' },
        { id: 'clean-musk', label: 'Clean Musk', labelAr: 'مسك نظيف', icon: 'Droplets' },
        { id: 'powdery-musk', label: 'Powdery Musk', labelAr: 'مسك بودري', icon: 'CloudSnow' },
        { id: 'animalic-musk', label: 'Animalic Musk', labelAr: 'مسك حيواني', icon: 'HelpCircle' },
        { id: 'synthetic-musk', label: 'Synthetic Musk', labelAr: 'مسك صناعي', icon: 'CircleDot' },
        { id: 'musk-tahara', label: 'Musk Tahara', labelAr: 'مسك الطهارة', icon: 'Moon' },
    ],
    leatherSmoky: [
        { id: 'leather', label: 'Leather', labelAr: 'جلد', icon: 'Shirt' },
        { id: 'suede', label: 'Suede', labelAr: 'شمواه', icon: 'Shirt' },
        { id: 'tobacco', label: 'Tobacco', labelAr: 'تبغ', icon: 'Cigarette' },
        { id: 'smoke', label: 'Smoke', labelAr: 'دخان', icon: 'Wind' },
        { id: 'birch-tar', label: 'Birch Tar', labelAr: 'قطران البتولا', icon: 'TreePine' },
        { id: 'ashes', label: 'Ashes', labelAr: 'رماد', icon: 'CloudSnow' },
        { id: 'gunpowder', label: 'Gunpowder', labelAr: 'بارود', icon: 'Zap' },
        { id: 'whiskey', label: 'Whiskey', labelAr: 'ويسكي', icon: 'Wine' },
        { id: 'rum', label: 'Rum', labelAr: 'روم', icon: 'Wine' },
        { id: 'burnt-wood', label: 'Burnt Wood', labelAr: 'خشب محترق', icon: 'Flame' },
        { id: 'campfire', label: 'Campfire', labelAr: 'نار المخيم', icon: 'Flame' },
    ],
    earthyGreen: [
        { id: 'moss', label: 'Moss', labelAr: 'طحلب', icon: 'LeafyGreen' },
        { id: 'oakmoss', label: 'Oakmoss', labelAr: 'طحلب البلوط', icon: 'Trees' },
        { id: 'patchouli', label: 'Patchouli', labelAr: 'باتشولي', icon: 'LeafyGreen' },
        { id: 'vetiver', label: 'Vetiver', labelAr: 'فيتيفر', icon: 'LeafyGreen' },
        { id: 'hay', label: 'Hay', labelAr: 'قش', icon: 'LeafyGreen' },
        { id: 'grass', label: 'Grass', labelAr: 'عشب', icon: 'LeafyGreen' },
        { id: 'hemp', label: 'Hemp', labelAr: 'قنب', icon: 'LeafyGreen' },
        { id: 'fig-leaf', label: 'Fig Leaf', labelAr: 'ورق التين', icon: 'Leaf' },
        { id: 'tomato-leaf', label: 'Tomato Leaf', labelAr: 'ورق الطماطم', icon: 'Leaf' },
        { id: 'galbanum', label: 'Galbanum', labelAr: 'جلبانوم', icon: 'LeafyGreen' },
        { id: 'violet-leaf', label: 'Violet Leaf', labelAr: 'ورق البنفسج', icon: 'Leaf' },
        { id: 'ivy', label: 'Ivy', labelAr: 'لبلاب', icon: 'LeafyGreen' },
        { id: 'fern', label: 'Fern', labelAr: 'سرخس', icon: 'LeafyGreen' },
    ],
    fruity: [
        { id: 'apple', label: 'Apple', labelAr: 'تفاح', icon: 'Apple' },
        { id: 'peach', label: 'Peach', labelAr: 'خوخ', icon: 'Cherry' },
        { id: 'apricot', label: 'Apricot', labelAr: 'مشمش', icon: 'Cherry' },
        { id: 'plum', label: 'Plum', labelAr: 'برقوق', icon: 'Cherry' },
        { id: 'cherry', label: 'Cherry', labelAr: 'كرز', icon: 'Cherry' },
        { id: 'raspberry', label: 'Raspberry', labelAr: 'توت العليق', icon: 'Cherry' },
        { id: 'strawberry', label: 'Strawberry', labelAr: 'فراولة', icon: 'Cherry' },
        { id: 'blackberry', label: 'Blackberry', labelAr: 'توت أسود', icon: 'Cherry' },
        { id: 'blackcurrant', label: 'Blackcurrant', labelAr: 'كشمش أسود', icon: 'Grape' },
        { id: 'fig', label: 'Fig', labelAr: 'تين', icon: 'LeafyGreen' },
        { id: 'pomegranate', label: 'Pomegranate', labelAr: 'رمان', icon: 'Cherry' },
        { id: 'passion-fruit', label: 'Passion Fruit', labelAr: 'فاكهة العاطفة', icon: 'Cherry' },
        { id: 'mango', label: 'Mango', labelAr: 'مانجو', icon: 'Cherry' },
        { id: 'pineapple', label: 'Pineapple', labelAr: 'أناناس', icon: 'Citrus' },
        { id: 'banana', label: 'Banana', labelAr: 'موز', icon: 'Banana' },
        { id: 'melon', label: 'Melon', labelAr: 'شمام', icon: 'Circle' },
        { id: 'watermelon', label: 'Watermelon', labelAr: 'بطيخ', icon: 'Circle' },
        { id: 'lychee', label: 'Lychee', labelAr: 'ليتشي', icon: 'Cherry' },
        { id: 'grape', label: 'Grape', labelAr: 'عنب', icon: 'Grape' },
        { id: 'date', label: 'Date', labelAr: 'تمر', icon: 'Nut' },
    ],
    middleEastern: [
        { id: 'oud-cambodian', label: 'Oud Cambodian', labelAr: 'عود كمبودي', icon: 'TreePine' },
        { id: 'oud-hindi', label: 'Oud Hindi', labelAr: 'عود هندي', icon: 'TreePine' },
        { id: 'oud-laotian', label: 'Oud Laotian', labelAr: 'عود لاوسي', icon: 'TreePine' },
        { id: 'taif-rose', label: 'Taif Rose', labelAr: 'ورد الطائف', icon: 'Flower2' },
        { id: 'arabian-jasmine', label: 'Arabian Jasmine', labelAr: 'ياسمين عربي', icon: 'Flower' },
        { id: 'bakhoor', label: 'Bakhoor', labelAr: 'بخور', icon: 'Flame' },
        { id: 'bukhoor', label: 'Bukhoor', labelAr: 'بخور', icon: 'Flame' },
        { id: 'musk-tahara', label: 'Musk Tahara', labelAr: 'مسك الطهارة', icon: 'Moon' },
        { id: 'dehn-al-oud', label: 'Dehn Al Oud', labelAr: 'دهن العود', icon: 'Droplets' },
        { id: 'amber-sakhawi', label: 'Amber Sakhawi', labelAr: 'عنبر سخاوي', icon: 'Gem' },
        { id: 'sandal-hindi', label: 'Sandal Hindi', labelAr: 'صندل هندي', icon: 'TreePine' },
        { id: 'musk-madinah', label: 'Musk Al Madinah', labelAr: 'مسك المدينة', icon: 'Moon' },
        { id: 'henna', label: 'Henna', labelAr: 'حناء', icon: 'LeafyGreen' },
        { id: 'attar', label: 'Attar', labelAr: 'عطر', icon: 'Droplets' },
    ],
};

// Note categories for the quiz UI
export const noteCategories: NoteCategory[] = [
    { id: 'freshCitrus', label: 'Fresh & Citrus', labelAr: 'منعش وحمضيات', icon: 'Citrus', description: '20 notes' },
    { id: 'floral', label: 'Floral', labelAr: 'زهري', icon: 'Flower2', description: '20 notes' },
    { id: 'sweetGourmand', label: 'Sweet & Gourmand', labelAr: 'حلو', icon: 'Cookie', description: '20 notes' },
    { id: 'woody', label: 'Woody', labelAr: 'خشبي', icon: 'Trees', description: '20 notes' },
    { id: 'spicy', label: 'Spicy', labelAr: 'حار', icon: 'Flame', description: '18 notes' },
    { id: 'amberyResinous', label: 'Ambery & Resinous', labelAr: 'عنبري', icon: 'Gem', description: '13 notes' },
    { id: 'musky', label: 'Musky', labelAr: 'مسكي', icon: 'Circle', description: '10 notes' },
    { id: 'leatherSmoky', label: 'Leather & Smoky', labelAr: 'جلد ودخان', icon: 'Shirt', description: '11 notes' },
    { id: 'earthyGreen', label: 'Earthy & Green', labelAr: 'ترابي وأخضر', icon: 'Sprout', description: '13 notes' },
    { id: 'fruity', label: 'Fruity', labelAr: 'فاكهي', icon: 'Apple', description: '20 notes' },
    { id: 'middleEastern', label: 'Middle Eastern', labelAr: 'شرقي', icon: 'Flame', description: '14 notes' },
];

// Get all notes as a flat array
export const allNotes = Object.values(fragranceNotes).flat();

export const uniqueAllNotes = Array.from(
    new Map(allNotes.map(note => [note.id, note])).values()
);

// Popular notes for quick selection (most common preferences)
export const popularNotes: FragranceNote[] = [
    { id: 'vanilla', label: 'Vanilla', labelAr: 'فانيليا', icon: 'Droplets' },
    { id: 'rose', label: 'Rose', labelAr: 'ورد', icon: 'Flower2' },
    { id: 'oud', label: 'Oud', labelAr: 'عود', icon: 'TreePine' },
    { id: 'jasmine', label: 'Jasmine', labelAr: 'ياسمين', icon: 'Flower' },
    { id: 'sandalwood', label: 'Sandalwood', labelAr: 'صندل', icon: 'TreePine' },
    { id: 'bergamot', label: 'Bergamot', labelAr: 'برغموت', icon: 'Citrus' },
    { id: 'musk', label: 'Musk', labelAr: 'مسك', icon: 'Circle' },
    { id: 'amber', label: 'Amber', labelAr: 'عنبر', icon: 'Gem' },
    { id: 'coffee', label: 'Coffee', labelAr: 'قهوة', icon: 'Coffee' },
    { id: 'lavender', label: 'Lavender', labelAr: 'لافندر', icon: 'Flower2' },
    { id: 'tobacco', label: 'Tobacco', labelAr: 'تبغ', icon: 'Cigarette' },
    { id: 'leather', label: 'Leather', labelAr: 'جلد', icon: 'Shirt' },
];

// Notes commonly avoided
export const commonlyAvoidedNotes: FragranceNote[] = [
    { id: 'oud', label: 'Heavy Oud', labelAr: 'عود ثقيل', icon: 'TreePine' },
    { id: 'rose', label: 'Strong Rose', labelAr: 'ورد قوي', icon: 'Flower2' },
    { id: 'vanilla', label: 'Heavy Vanilla', labelAr: 'فانيليا ثقيلة', icon: 'Droplets' },
    { id: 'musk', label: 'Strong Musk', labelAr: 'مسك قوي', icon: 'Circle' },
    { id: 'tobacco', label: 'Tobacco', labelAr: 'تبغ', icon: 'Cigarette' },
    { id: 'patchouli', label: 'Patchouli', labelAr: 'باتشولي', icon: 'LeafyGreen' },
    { id: 'leather', label: 'Leather', labelAr: 'جلد', icon: 'Shirt' },
    { id: 'smoke', label: 'Smoke', labelAr: 'دخان', icon: 'Wind' },
    { id: 'incense', label: 'Incense', labelAr: 'بخور', icon: 'Flame' },
    { id: 'animalic', label: 'Animalic Notes', labelAr: 'روائح حيوانية', icon: 'HelpCircle' },
    { id: 'powdery', label: 'Powdery Notes', labelAr: 'روائح بودرية', icon: 'CloudSnow' },
    { id: 'aquatic', label: 'Aquatic/Marine', labelAr: 'مائي/بحري', icon: 'Waves' },
    { id: 'none', label: "I'm open to anything!", labelAr: 'منفتح على كل شيء', icon: 'Check' },
];

export const quizSteps: QuizStep[] = [
    {
        id: 1,
        name: 'gender',
        question: "Who is this fragrance for?",
        questionAr: "لمن هذا العطر؟",
        type: 'single',
        required: true,
        skippable: false,
        options: [
            { id: 'female', label: 'For Her', labelAr: 'للنساء', icon: 'User' },
            { id: 'male', label: 'For Him', labelAr: 'للرجال', icon: 'UserCircle' },
            { id: 'unisex', label: 'Unisex', labelAr: 'للجنسين', icon: 'Sparkles' }
        ]
    },
    {
        id: 2,
        name: 'favoriteNotes',
        question: "Which notes do you love?",
        questionAr: "ما النوتات التي تحبها؟",
        type: 'multiple',
        required: false,
        skippable: true,
        options: [
            { id: 'none', label: "No specific notes", labelAr: 'لا يوجد', icon: 'Check' },
            ...uniqueAllNotes
        ]
    },
    {
        id: 3,
        name: 'avoidedNotes',
        question: "Any notes you avoid?",
        questionAr: "هل هناك نوتات تريد تجنبها؟",
        type: 'multiple',
        required: false,
        skippable: true,
        options: [
            { id: 'none', label: "I'm open to anything!", labelAr: 'منفتح على كل شيء', icon: 'Check' },
            ...uniqueAllNotes
        ]
    },
    {
        id: 4,
        name: 'season',
        question: "When will you mostly wear this?",
        questionAr: "متى سترتدي هذا العطر؟",
        type: 'single',
        required: true,
        skippable: false,
        options: [
            { id: 'spring', label: 'Spring', labelAr: 'الربيع', icon: 'Flower2', description: 'Light & fresh' },
            { id: 'summer', label: 'Summer', labelAr: 'الصيف', icon: 'Sun', description: 'Citrus & aquatic' },
            { id: 'fall', label: 'Fall', labelAr: 'الخريف', icon: 'Leaf', description: 'Warm & spicy' },
            { id: 'winter', label: 'Winter', labelAr: 'الشتاء', icon: 'Snowflake', description: 'Rich & cozy' },
            { id: 'all', label: 'All Year', labelAr: 'طوال السنة', icon: 'Calendar', description: 'Versatile' }
        ]
    },
    {
        id: 5,
        name: 'intensity',
        question: "How strong do you like your fragrance?",
        questionAr: "ما مدى قوة العطر؟",
        type: 'single',
        required: true,
        skippable: false,
        options: [
            { id: 'light', label: 'Light & Subtle', labelAr: 'خفيف', icon: 'Wind', description: 'Close to skin' },
            { id: 'moderate', label: 'Moderate', labelAr: 'معتدل', icon: 'Gauge', description: 'Balanced' },
            { id: 'strong', label: 'Bold & Powerful', labelAr: 'قوي', icon: 'Zap', description: 'Statement maker' }
        ]
    }
];
